name: Build Rulebook PDF

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 2 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Pandoc
        uses: pandoc/actions/setup@v1

      - name: Install minimal LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base texlive-latex-recommended \
            texlive-fonts-recommended texlive-fonts-extra lmodern

      - name: Build PDF
        run: node scripts/build-pdf.js

      - name: Commit PDF to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          mkdir -p nightly-builds
          # Move the PDF to the nightly-builds folder with a consistent name
          mv dist/*.pdf nightly-builds/Ubyx-Rulebook-Nightly.pdf
          git add nightly-builds/Ubyx-Rulebook-Nightly.pdf
          # Commit and push, but only if there are changes
          git commit -m "docs(pdf): update nightly build" -a || echo "No changes to commit"
          git push
