name: Nightly PDF – Notion

on:
  # One‑time push trigger makes the workflow appear in Actions,
  # then it continues via manual dispatch or nightly schedule.
  push:
    branches: [ rulebook-sync ]

  workflow_dispatch:        # Run button in the Actions tab

  schedule:
    - cron: '0 2 * * *'     # 02 UTC every night

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_PAT:         ${{ secrets.GH_PAT }}
      NOTION_TOKEN:   ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      - name: Install script dependencies
        run: npm install glob node-fetch @notionhq/client

      - name: Build PDF and update Notion
        run: node scripts/nightly_pdf_sync.js
