name: Nightly PDF – Notion

on:
  push:
    branches: [ rulebook-sync ]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_PAT:         ${{ secrets.GH_PAT }}
      NOTION_TOKEN:   ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with: { node-version: '18' }

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      # ── minimal LaTeX + Latin Modern fonts ────────────────────────────────
      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            lmodern
      # ───────────────────────────────────────────────────────────────────────

      - name: Install script deps
        run: npm install glob node-fetch @notionhq/client

      - name: Build PDF and update Notion
        run: node scripts/nightly_pdf_sync.js
