name: Nightly Rulebook PDF Build

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 2 * * *'

jobs:
  call-workflow:
    name: Call Reusable Build Workflow
    # Calls the reusable workflow located in the nightly-build branch
    uses: pronouncedkenny/Ubyx-Rulebook/.github/workflows/build-pdf.yml@nightly-build
    permissions:
      # This permission is required for the called workflow to commit the PDF
      contents: write
