name: Sync Rulebook to Notion

on:
  push:
    branches: [ rulebook-sync ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ pull the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2 ▸ install Node and build the single markdown file
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build rulebook.md
        run: |
          npm install
          node scripts/build-rulebook.js

      # 3 ▸ push that markdown into Notion (no synced‑block wrapper)
      - name: Push Markdown to Notion
        uses: tryfabric/markdown-to-notion@main
        with:
          file: dist/rulebook.md
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_id:    ${{ secrets.NOTION_PAGE_ID }}
          delete_existing: true
          sync: false            # ← disables the 100‑child limit wrapper
