name: Sync Rulebook to Notion

on:
  push:
    branches: [ rulebook-sync ]   # run on every commit to this branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ pull the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2 ▸ install Node deps & build dist/rulebook.md
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build rulebook.md
        run: |
          npm install                 # installs 'glob' & writes package‑lock.json
          node scripts/build-rulebook.js

      # 3 ▸ push that markdown into Notion 
      - name: Push Markdown to Notion
        uses: JoshStern/push-md-to-notion@v0.3.0
        with:
          md_file: dist/rulebook.md
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-id:    ${{ secrets.NOTION_PAGE_ID }}
          delete-existing: true
