name: Sync Rulebook to Notion

on:
  push:
    branches: [ rulebook-sync ]

jobs:
  # ── 1 ▸ build the part files and export their paths ─────────────────────────
  build:
    runs-on: ubuntu-latest
    outputs:
      parts: ${{ steps.collect.outputs.parts }}
      first: ${{ steps.collect.outputs.first }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '18' }

      - name: Build rulebook part files
        run: |
          npm install
          node scripts/build-rulebook.js

      - id: collect
        run: |
          FILES=$(ls dist/parts/*.md | sort)
          echo "parts=$(echo "$FILES" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo "first=$(echo "$FILES" | head -n 1)" >> $GITHUB_OUTPUT
        shell: bash

  # ── 2 ▸ upload each part (first call deletes old content) ──────────────────
  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.build.outputs.parts) }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Upload part to Notion
        uses: tryfabric/markdown-to-notion@main
        with:
          file: ${{ matrix.file }}
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_id:    ${{ secrets.NOTION_PAGE_ID }}
          delete_existing: ${{ matrix.file == needs.build.outputs.first }}
