name: Sync Rulebook to Notion

on:
  push:
    branches: [ rulebook-sync ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }

      - name: Build rulebook.md
        run: |
          npm install glob
          node scripts/build-rulebook.js

      - name: Push Markdown to Notion
        uses: tryfabric/markdown-to-notion@main
        with:
          file: dist/rulebook.md
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_id:    ${{ secrets.NOTION_PAGE_ID }}
          delete_existing: true
          chunk_size: 50          # stream blocks in batches (well under 100)
