name: Sync Rulebook to Notion

on:
  push:
    branches: [ rulebook-sync ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. check out your repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0           # get full history (optional)

      # 2. set up Node and build the markdown file
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          npm install                   # installs glob from package.json
          node scripts/build-rulebook.js

      # 3. push that markdown into Notion
      - name: Push Markdown to Notion
        uses: JoshStern/push-md-to-notion@v0.3.0
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}




